title: Test Document
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://zombiedogz.github.io/Doc_test/

baseurl: "/Doc_test" 
color_scheme: dark

plugins:
  - jekyll-default-layout
